import Head from 'next/head'
import Header from '@/components/Header/Header'
import Social from '@/components/Social/Social'

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Social/>
        <Header/>
      </main>
    </>
  )
}
